services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/mlruns
    ports:
      - "8080:8080"
    volumes:
      - ./mlflow:/mlflow

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data

  minio-mc:
    image: quay.io/minio/mc
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minio}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minio123}
    entrypoint: >
      /bin/sh -c "
        echo "da";
        until mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
          echo 'waiting for minio...'; sleep 2;
        done;
        sleep 5;
        echo "$MINIO_ROOT_USER";
        mc mb -p minio/mlops-data || true;
        mc anonymous set download minio/mlops-data || true;
        if [ -d /input/imdb ]; then
          mc mirror --overwrite /input/imdb minio/mlops-data/imdb;
        else
          echo 'No local data at /input/imdb to upload';
        fi;
        tail -f /dev/null
      "
    volumes:
      - ./data/IMDb:/input/imdb:ro

  app:
    build: .
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8080
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minio}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minio123}
      - DVC_REMOTE=minio
    depends_on:
      - mlflow
      - minio
    command: tail -f /dev/null
