services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.1
    command: >
      mlflow server
      --host 0.0.0.0
      --port 8080
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/mlruns
    ports:
      - "8080:8080"
    volumes:
      - ./mlflow:/mlflow

  app:
    build: .
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:8080
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER:-minio}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD:-minio123}
      - DVC_REMOTE=minio
    depends_on:
      - mlflow
      - minio
    command: tail -f /dev/null

  triton:
    #image: ghcr.io/triton-inference-server/server:23.10-py3
    #image: nvcr.io/nvidia/tritonserver:25.12-trtllm-python-py3
    image: nvcr.io/nvidia/tritonserver:23.10-py3

    platform: linux/amd64
    command: >
      tritonserver
      --model-repository=/models
      --disable-auto-complete-config
      --backend-config=onnxruntime,execution_mode=ORT_SEQUENTIAL
      --http-port=8000 --grpc-port=8001 --metrics-port=8002
    volumes:
      - ./model-repo:/models:ro
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
